### ISSUE TITLE
Both the internal mail composer, and the mailto app, are triggered when clicking on the attendee response bluebar

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-inbox#121]
**reproduction steps**
* have an event invitation response
* click on the user's name in the blue bar
![image](https://user-images.githubusercontent.com/1465817/92492129-49756a00-f1f3-11ea-9d3e-5719c0c4c092.png)

**Expected behaviour**
A new composer popin opens, with the `to` field set as the user email address

**Current behaviour**
- A new composer popin opens, with the `to` field set as the user email address
- A new browser tab is opened with the mailto app. (see also bug https://github.com/OpenPaaS-Suite/esn-frontend-mailto/issues/49 )

**Comment by billyfrost418** [comment]
I cannot reproduce this bug on [dev platform](https://dev.open-paas.org/) since there is no response email after creating an event and inviting other members.
However, on [production](https://openpaas.linagora.com/), this bug is no longer occurs. Below is the behavior when I click on the username in the invitation response.
Please test this again. Thank you

![ezgif-6-6f8e90a8b1aa](https://user-images.githubusercontent.com/26143938/93058253-5386e500-f699-11ea-9599-cd5e76836f32.gif)
[Video](https://streamable.com/x0thpg)
