### ISSUE TITLE
Closing email composer is wrong on mobile

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-inbox#128]
On mobile, compose an email and discard it by clicking on the close button or send it: closes the composer but do like some history.back which does not resolve a inbox state. When opening inbox by setting the URL when I was browsing just before on http://something, closing the composer closes inbox and reopen http://something

![inbox](https://user-images.githubusercontent.com/264403/92695561-ea296e00-f348-11ea-9828-c687e8894cc5.gif)

**Comment by rezk2ll** [comment]
not just mobile, the bug also appears for desktop ( if you use the composer with a link: `/inbox/#/unifiedinbox/compose`

![composer-bug](https://user-images.githubusercontent.com/6764881/93068997-0bee6200-f675-11ea-9a93-2942da07139f.gif)

**Comment by tlle14** [comment]
Hi @chamerling @rezk2ll 

The issue is no longer existing when closing the composer on mobile. 
But the expected result should be: After closing the composer, it should return to the previous state. 

Example:
1. User is in Inbox
2.  User navigates to the Sent mailbox
3.  Open the composer then sent an email
=> After closing the composer, it displays Inbox mailbox. 
Expected: It should display the Sent mailbox.
