### ISSUE TITLE
"Reply" button acts like "reply all" button

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-inbox#325]
# Precondition
An email is sent to multiple recipients

# Actual Result
When a recipient clicks a "Reply" button, it opens the composer with multiple recipients.
![Peek 2021-01-10 16-52](https://user-images.githubusercontent.com/69950655/104119959-e5f87600-5365-11eb-9e6c-ed0f91fcbf2c.gif)

# Expected Result
It should reply to the sender only

# Environment
Production

**Comment by oubchid** [comment]
@hantt12 

It's not acts like "reply all" cause when "reply all" we keep all properties "CC" and "BCC", unlike "reply" we keep only "TO".

Maybe the solution adding here https://github.com/OpenPaaS-Suite/esn-frontend-inbox/commit/442d94d0180ac9a5b7c3f7d0a8acc34e35e932db, need to be checked, that is the expected behavior.

Need to check the two cases:
1. If you send a mail with multiple "to" and go to "sent email" and you reply a mail.
2. if you receive a mail with multiple "to" and you go to inbox then reply a mail.
